pod 'HMSegmentedControl', '~> 1.5.2'
pod 'SwipeView', '~> 1.3.2'
pod 'BFPaperButton', '~> 2.0.27'
pod 'Masonry', '~> 1.0.0'
pod 'DWBubbleMenuButton', '~> 1.0.1'
pod 'MCFireworksButton', '~> 0.1'
pod 'DCPathButton', '~> 2.1.3'
pod 'SWRevealViewController', '~> 2.3.0'